version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8001:8000"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    command: >
      sh -lc "\
      composer install --no-interaction --prefer-dist --optimize-autoloader && \
      [ -f .env ] || cp .env.example .env && \
      if ! grep -q '^APP_KEY=' .env || [ -z \"$(grep '^APP_KEY=' .env | cut -d= -f2)\" ]; then php artisan key:generate --force; fi && \
      chmod -R 775 storage bootstrap/cache && \
      php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - dubbing-network

networks:
  dubbing-network:
    driver: bridge
