version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8001:8000"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    command:
      - sh
      - -lc
      - |
          set -e
          composer install --no-interaction --prefer-dist --optimize-autoloader
          [ -f .env ] || cp .env.example .env
          if grep -q '^APP_KEY=.' .env; then echo "APP_KEY mevcut, atlanıyor"; else php artisan key:generate --force; fi
          mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs bootstrap/cache
          chown -R www-data:www-data storage bootstrap/cache
          chmod -R ug+rwX storage bootstrap/cache
          php artisan config:clear || true
          php artisan route:clear || true
          php artisan view:clear || true
          php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - dubbing-network

networks:
  dubbing-network:
    driver: bridge
