services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-app
    restart: unless-stopped
    working_dir: /var/www/html
    # PROD: Kod bind-mount edilmez, image içindeki vendor korunur
    volumes:
      - app_storage:/var/www/html/storage
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8001:8000"
    environment:
      # Uzak DB bilgilerinizi .env yerine burada da verebilirsiniz
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CHARSET: utf8mb4
      DB_COLLATION: utf8mb4_unicode_ci

volumes:
  app_storage:
    driver: local


